test_firstp (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_firstp (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_firstp
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/yuanyuanhe/PycharmProjects/zspaimai_ui/test/test_firstp.py", line 5, in <module>
    from .init import Init2, Init3, Init4, Init5, Init
ImportError: attempted relative import with no known parent package


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
