ERROR 2021-11-06 09:36:25,003 assertbase.py _teardown_collect 261 <bound method MockTest.test_mock_request of <mocktest.MockTest testMethod=test_mock_request>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/minium-1.0.8-py3.9.egg/minium/framework/libs/unittest/suite.py", line 32, in _handleClassSetUp
    _miniClassSetUp()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/minium-1.0.8-py3.9.egg/minium/framework/minitest.py", line 489, in _miniClassSetUp
    cls.mini = get_minium(cls.CONFIG)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/minium-1.0.8-py3.9.egg/minium/framework/minitest.py", line 89, in get_minium
    g_minium = minium.miniprogram.get_minium_driver(conf=cfg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/minium-1.0.8-py3.9.egg/minium/miniprogram/__init__.py", line 30, in get_minium_driver
    return APP[application](conf, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/minium-1.0.8-py3.9.egg/minium/miniprogram/wx_minium.py", line 93, in __init__
    self.launch_dev_tool()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/minium-1.0.8-py3.9.egg/minium/miniprogram/base_driver/minium_log.py", line 135, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/minium-1.0.8-py3.9.egg/minium/miniprogram/wx_minium.py", line 117, in launch_dev_tool
    raise MiniConfigError("project_path: %s not exists" % self.project_path)
minium.framework.exception.MiniConfigError: project_path: /Users/sherlock/github/miniprogram-demo not exists
